### ISSUE TITLE
Unfollow Error

### ISSUE THREAD

**Issue by MiBingy** [yousefissa/Twitter-Follow-and-Unfollow-Bot#19]
I just got the bot up and running and it seems that I have ran into a problem. The bot was working perfectly fine for me yesterday and today when it came to following users, but when I began unfollowing users that don't follow me back I started having problems. The first time I ran the command I got about 90 unfollowed accounts before it started giving me the error message. Now, every time that I try to run the command, it either shows me the "do you want to continue?" prompt or it continues to run but only displaying an error message every 10 seconds. It almost seems like the bot completely detaches from my account once I run that command. Was wondering if you knew about this or if there was a fix.

**Comment by luisramirezdev** [comment]
Maybe is problem with Twitter API credetentials?
