### ISSUE TITLE
Error screen_name

### ISSUE THREAD

**Issue by luisramirezdev** [yousefissa/Twitter-Follow-and-Unfollow-Bot#3]
Hello,

First, thanks for sharing your code.

I have a problem with `screen_name`, to solve it I had to add a line of code in `twitterBot.py`, this way my bot worked.

`screen_name = config_data ["auth"] ["screen_name"]`

I do not know if something is missing in the code.

Sorry for my bad English

**Comment by yousefissa** [comment]
Thanks for that! 

Your english is fine. I will do some more testing on this tonight.
