### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by theolux** [yousefissa/Twitter-Follow-and-Unfollow-Bot#5]
Hi,

First, I want to thank you for creating this script, it should be highly useful!

I tried running it for the first time now, and I already received a 'NameError: name 'raw_input' is not defined' error. I fixed it by replacing 'raw_input' with 'input', but now when trying to follow users based on keywords I set in 'config.json', it says 'Starting to follow...' but doesn't actually follow anybody, outputs 0 and then asks if I want to keep going.

Is just that the whole script is based on an older version of python and that's why it doesn't work properly or is it something else?

Following the followers of another user works great though!
Regardless, I would appreciate if you update the code to the latest version of python for user convenience (I'm using python 3.6).

Also, should I be worried about getting banned? What are the limitations and are you planning on adding limitation options to the script?

Thanks!

**Comment by yousefissa** [comment]
I accepted a pull request and he switched it to Python 2. I will revert back now.

**Comment by yousefissa** [comment]
As far as limitations, i've had different experiences with different account.

**Comment by yousefissa** [comment]
Today I will go through all of the code and rewrite it and test every feature to make sure it still works.
